@report.api = http://localhost:5012/api/reports

### create report
POST {{report.api}}

### get all reports
GET {{report.api}}

### get report by id
@report.id = 75ce635e-6f43-4559-982d-694986f7f7d1
GET {{report.api}}/{{report.id}}

### get report data
GET {{report.api}}/{{report.id}}/data
