// <auto-generated />
using System;
using ContactManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContactManagementDbContext))]
    [Migration("20250810121639_EnableCascadingDeletionForContactEntity")]
    partial class EnableCascadingDeletionForContactEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactManagement.Infrastructure.Data.Entities.ContactDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_details");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_details_id");

                    b.HasIndex("ContactId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_details_contact_id_id");

                    b.ToTable("contact_details", (string)null);
                });

            modelBuilder.Entity("ContactManagement.Infrastructure.Data.Entities.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("ContactManagement.Infrastructure.Data.Entities.ContactDetailEntity", b =>
                {
                    b.HasOne("ContactManagement.Infrastructure.Data.Entities.ContactEntity", "Contact")
                        .WithMany("ContactDetails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_details_contacts_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ContactManagement.Infrastructure.Data.Entities.ContactEntity", b =>
                {
                    b.Navigation("ContactDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
