@contacts.api = http://localhost:5074/api/contacts

### create contact
POST {{contacts.api}}
Content-Type: application/json

{
    "name": "Evdile",
    "surname": "yildiz2",
    "company" : "Zila"
}

### Get all contacts
GET {{contacts.api}}
Accept: application/json


### Get contact
@contactid=0662534e-11f1-4e49-bc22-b915bbf7291d
GET {{contacts.api}}/{{contactid}}
Accept: application/json

### delete contact
DELETE {{contacts.api}}/{{contactid}}

### create contact detail
POST {{contacts.api}}/{{contactid}}/details
Content-Type: application/json

{
    "type": "Email",
    "value": "aa@g.comxx"
}

### get all contact details
GET {{contacts.api}}/{{contactid}}/details
Accept: application/json

### delete contact details
@contact.details.id=12b466f9-7414-46c1-a3e5-76304e5acef8
DELETE {{contacts.api}}/{{contactid}}/details/{{contact.details.id}}
